# Site settings
title: DataSift Bootstrap
description: 

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments

# post settings
permalink: /:year/:month/:day/:title/

collections:
  resources:
    output: false
  articles:
    output: true


defaults:
  -
    scope:
      path: "_resources/controls"
    values:
      layout: resource
      category: controls
  -
    scope:
      path: "_resources/design"
    values:
      layout: resource
      category: design

prose:
  rooturl: '_posts'
  siteurl: 'http://datasift.github.io/bootstrap'